baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Non-Fiction Author'
theme = 'dirk'
# theme = 'htw-boilerplate'

[build]
# Used by PurgeCSS
    writeStats = true

[menu]
[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = 100
[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/posts/'
  weight = 200
[[menu.main]]
  identifier = 'books'
  name = 'Books'
  url = '/books/'
  weight = 300
[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = 800
[[menu.main]]
  identifier = 'contact'
  name = 'Contact'
  url = '/contact/'
  weight = 900